        # params["modelname"] = "init" # for naming the .pkl file of the resulting simulation, and names the folders to save the model and its results in
        # params["Numsegs"] = 30
        # params["Numtypes"] = 1
        # params["typenames"] = ['I'] # name of each neuron type
        # params["colorlist"] = ['black'] # color of each type (in the same order as typenames)
        # params["simtime"] = 100 # Length of simulation (in ms) DAVID: changed name to avoid confusion with number of types
        # params["tstep"] = 0.1
        # params["speedmix"] = 0.5 # Irrelevant for models without fast and slow populations
        # params["fastdrivemod"] = 1.0 # Multiplies all fast drive connections
        # params["slowdrivemod"] = 1.0 # Multiplies all slow drive connections
        # params["fastmtc"] = 1.0 # Membrane time constant for neurons in the fast population
        # params["slowmtc"] = 10.0 # Membrane time constant for neurons in the slow population
        # params["timedelay_off"] = False # Eliminates all time delays for neuron connections
        # params["delayts"] = 1.0 # number of time steps to equal base delay amount (5 = 0.5ms with tstep=0.1)
        # params["eibalanced"] = False # If on, it renormalizes network to ensure ei-balance 
        # params["esumadd"] = 0 # Irrelevant if eibalanced is False: controls E/I normalization balance
        # params["phasemax"] = 0.8 # phasemax and phasemin define the relationship between (desired) phase and connectivity
        # params["phasemin"] = 0.3 # Note: sometimes 0.75 and 0.25 work, even though it kind of shouldn't??
        # params["Cstrength"] = 0.5 # Overall connectivity factor
        # params["Estrength"] = 1.0 
        # params["Istrength"] = 1.0
        # params["drive"] = 1.0 # Strength of the tonic drive
        # # params["Iboost"] = 1.0 # Multiplies all I connections DAVID: redundant with Istrength
        # params["cutoff"] = 30 # Global (type-specific restraints make this redundant if they are lesser)
        # params["Icutoff"] = 13 # how far I neurons project caudally (up to global limit)
        # params["Edes_cutoff"] = 13 # how far E neurons project caudally (up to global limit)
        # params["firstEcutoff"] = 2 # size of the 'E gap'
        # params["Easc_cutoff"] = 0 # Make >0 to allow ascending E connections
        # # params["Espread"] = 1.0 # Projecting E connections are divided by this factor (1=do nothing, which typically works) DAVID: Redundant with Estrength
        # params["driveslope"] = 0.0 # FAILED (so far!!): can shape tonic drive spatially (combine with descending E!)
        # params["Eablation"] = 1.0 
        # params["Iipsiablation"] = 1.0
        # params["Icontraablation"] = 1.0
        # params["Edes_cutoff_fast"] = 13
        # params["Edes_cutoff_slow"] = 13

from copy import deepcopy

def load_default_params(pname):
    result = {}
    if pname == "1pop":
        result = deepcopy(params_1pop)
    elif pname == "2pop":
        result = deepcopy(params_2pop)
    elif pname == "3pop":
        result = deepcopy(params_3pop)
    elif pname == "6pop":
        result = deepcopy(params_6pop)
    elif pname == "8pop":
        result = deepcopy(params_8pop)
    else:
        print("Could not find default params with name {}. Returning '1pop' default instead.".format(pname))
        result = deepcopy(params_1pop)
    return result

# Defaults for model with 1 population
params_1pop = {}
params_1pop["modelname"] = "1pop"
params_1pop["Numsegs"] = 30
params_1pop["Numtypes"] = 1
params_1pop["typenames"] = ['I']
params_1pop["colorlist"] = ['black']
params_1pop["rngseed"] = 27
params_1pop["simtime"] = 600
params_1pop["tstep"] = 0.1
params_1pop["speedmix"] = 0.5
params_1pop["fastdrivemod"] = 1.0
params_1pop["slowdrivemod"] = 1.0
params_1pop["fastmtc"] = 1.0
params_1pop["slowmtc"] = 10.0
params_1pop["timedelay_off"] = False
params_1pop["delayts"] = 10.0
params_1pop["eibalanced"] = False
params_1pop["esumadd"] = 0
params_1pop["phasemax"] = 0.8 
params_1pop["phasemin"] = 0.3
params_1pop["Cstrength"] = 0.5 
params_1pop["Estrength"] = 1.0
params_1pop["Istrength"] = 1.0
params_1pop["drive"] = 1.0 
params_1pop["Iboost"] = 1.0
params_1pop["cutoff"] = 30 
params_1pop["Icutoff"] = 13 
params_1pop["Edes_cutoff"] = 13 
params_1pop["firstEcutoff"] = 2 
params_1pop["Easc_cutoff"] = 0 
params_1pop["Espread"] = 1.0
params_1pop["driveslope"] = 0.0
params_1pop["Eablation"] = 1.0
params_1pop["Iipsiablation"] = 1.0
params_1pop["Icontraablation"] = 1.0
params_1pop["Edes_cutoff_fast"] = 13
params_1pop["Edes_cutoff_slow"] = 13

# Defaults for the model with 2 populations (fast and slow)
params_2pop = {}
params_2pop["modelname"] = "2pop"
params_2pop["Numsegs"] = 30
params_2pop["Numtypes"] = 2
params_2pop["typenames"] = ['I fast', 'I slow']
params_2pop["colorlist"] = ['red', 'red']
params_2pop["rngseed"] = 27
params_2pop["simtime"] = 600
params_2pop["tstep"] = 0.1
params_2pop["speedmix"] = 0.5
params_2pop["fastdrivemod"] = 1.0
params_2pop["slowdrivemod"] = 1.0
params_2pop["fastmtc"] = 1.0
params_2pop["slowmtc"] = 10.0
params_2pop["timedelay_off"] = False
params_2pop["delayts"] = 10
params_2pop["fastdelayts"] = 2
params_2pop["slowdelayts"] = 5
params_2pop["eibalanced"] = False
params_2pop["esumadd"] = 0
params_2pop["phasemax"] = 0.8 
params_2pop["phasemin"] = 0.3
params_2pop["Cstrength"] = 0.5 
params_2pop["Estrength"] = 1.0
params_2pop["Istrength"] = 1.0
params_2pop["drive"] = 1.0 
params_2pop["Iboost"] = 1.0
params_2pop["cutoff"] = 30 
params_2pop["Icutoff"] = 13 
params_2pop["Edes_cutoff"] = 16
params_2pop["firstEcutoff"] = 2 
params_2pop["Easc_cutoff"] = 0 
params_2pop["Espread"] = 1.0
params_2pop["driveslope"] = 0.0
params_2pop["Eablation"] = 1.0
params_2pop["Iipsiablation"] = 1.0
params_2pop["Icontraablation"] = 1.0
params_2pop["Edes_cutoff_fast"] = 13
params_2pop["Edes_cutoff_slow"] = 13

# Defaults for the model with 3 populations (I ipsi, I contra, and E)
params_3pop = {}
params_3pop["modelname"] = "3pop"
params_3pop["Numsegs"] = 30
params_3pop["Numtypes"] = 3
params_3pop["typenames"] = ['I ipsi', 'I contra', 'E']
params_3pop["colorlist"] = ['red', 'blue', 'green']
params_3pop["rngseed"] = 27
params_3pop["simtime"] = 600
params_3pop["tstep"] = 0.1
params_3pop["speedmix"] = 0.5
params_3pop["fastdrivemod"] = 1.0
params_3pop["slowdrivemod"] = 1.0
params_3pop["fastmtc"] = 1.0
params_3pop["slowmtc"] = 1.0
params_3pop["timedelay_off"] = False
params_3pop["delayts"] = 2
params_3pop["eibalanced"] = False
params_3pop["esumadd"] = 0
params_3pop["phasemax"] = 0.8 
params_3pop["phasemin"] = 0.3
params_3pop["Cstrength"] = 0.5 
params_3pop["Estrength"] = 1.0
params_3pop["Istrength"] = 1.0
params_3pop["drive"] = 1.0 
params_3pop["Iboost"] = 1.0
params_3pop["cutoff"] = 30 
params_3pop["Icutoff"] = 13 
params_3pop["Edes_cutoff"] = 16 
params_3pop["firstEcutoff"] = 2 
params_3pop["Easc_cutoff"] = 0 
params_3pop["Espread"] = 1.0
params_3pop["driveslope"] = 0.0
params_3pop["Eablation"] = 1.0
params_3pop["Iipsiablation"] = 1.0
params_3pop["Icontraablation"] = 1.0
params_3pop["Edes_cutoff_fast"] = 16
params_3pop["Edes_cutoff_slow"] = 16

# Defaults for the model with 6 populations (ipsi, contra, and E in both fast and slow)
params_6pop = {}
params_6pop["modelname"] = "6pop"
params_6pop["Numsegs"] = 30
params_6pop["Numtypes"] = 6
params_6pop["typenames"] = ['I ipsi fast', 'I ipsi slow', 'I contra fast', 'I contra slow', 'E fast', 'E slow']
params_6pop["colorlist"] = ['red', 'red', 'blue', 'blue', 'green', 'green']
params_6pop["rngseed"] = 27
params_6pop["simtime"] = 600
params_6pop["tstep"] = 0.1
params_6pop["speedmix"] = 0.5
params_6pop["fastdrivemod"] = 1.0
params_6pop["slowdrivemod"] = 1.0
params_6pop["fastmtc"] = 1.0
params_6pop["slowmtc"] = 10.0
params_6pop["timedelay_off"] = False
params_6pop["delayts"] = 10.0
params_6pop["eibalanced"] = False
params_6pop["esumadd"] = 0
params_6pop["phasemax"] = 0.8 
params_6pop["phasemin"] = 0.3
params_6pop["Cstrength"] = 0.5 
params_6pop["Estrength"] = 1.0
params_6pop["Istrength"] = 1.0
params_6pop["drive"] = 1.0 
params_6pop["Iboost"] = 1.0
params_6pop["cutoff"] = 30 
params_6pop["Icutoff"] = 13 
params_6pop["Edes_cutoff"] = 16 
params_6pop["firstEcutoff"] = 2 
params_6pop["Easc_cutoff"] = 0 
params_6pop["Espread"] = 1.0
params_6pop["driveslope"] = 0.0
params_6pop["Eablation"] = 1.0
params_6pop["Iipsiablation"] = 1.0
params_6pop["Icontraablation"] = 1.0
params_6pop["Edes_cutoff_fast"] = 16
params_6pop["Edes_cutoff_slow"] = 16

params_8pop = {}
params_8pop["modelname"] = "8pop"
params_8pop["Numsegs"] = 30
params_8pop["Numtypes"] = 8
params_8pop["typenames"] = ['I ipsi asc fast', 'I ipsi asc slow', 'I ipsi des fast', 'I ipsi des slow', 'I contra fast', 'I contra slow', 'E fast', 'E slow']
params_8pop["colorlist"] = ['red', 'red', 'orangered', 'orangered', 'blue', 'blue', 'green', 'green']
params_8pop["rngseed"] = 27
params_8pop["simtime"] = 600
params_8pop["tstep"] = 0.1
params_8pop["speedmix"] = 0.5
params_8pop["fastdrivemod"] = 1.0
params_8pop["slowdrivemod"] = 1.0
params_8pop["fastmtc"] = 1.0
params_8pop["slowmtc"] = 10.0
params_8pop["timedelay_off"] = False
params_8pop["delayts"] = 10.0
params_8pop["fastdelayts"] = 2
params_8pop["slowdelayts"] = 5
params_8pop["eibalanced"] = False
params_8pop["esumadd"] = 0
params_8pop["phasemax"] = 0.8 
params_8pop["phasemin"] = 0.3
params_8pop["Cstrength"] = 0.5 
params_8pop["Estrength"] = 0.5
params_8pop["Istrength"] = 1.0
params_8pop["drive"] = 1.0 
params_8pop["Iboost"] = 1.0
params_8pop["cutoff"] = 30 
params_8pop["Icutoff"] = 13 
params_8pop["Edes_cutoff"] = 16
params_8pop["firstEcutoff"] = 2 
params_8pop["Easc_cutoff"] = 0 
params_8pop["Espread"] = 1.0
params_8pop["driveslope"] = 0.0
params_8pop["Eablation"] = 1.0
params_8pop["Iipsiablation"] = 1.0
params_8pop["Iipsiascablation"] = 1.0
params_8pop["Iipsidesablation"] = 1.0
params_8pop["Icontraablation"] = 1.0
params_8pop["Edes_cutoff_fast"] = 16
params_8pop["Edes_cutoff_slow"] = 4
